Feature/flows tab [WTEL-4355]
webitel/cc-workspaces pull request #384
Opened 2024-04-25 22:25 UTC by liza-pohranichna

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/components/the-agent-info-section.vue
> +        icon: 'ws-flows',
а ти хіба не в лібу додала іконку?

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +  <section class="flows">
назва классу має бути як і компонента)

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +const isLoaded = ref(false);
а компонент лоадера тут не потрібен?

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +const team = computed(() => store.getters['ui/infoSec/agentInfo/AGENT_TEAM']);
Можна використати agentNamespace)

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +const flowsList = ref([]);
reactive)

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +async function loadFlowsList(id) {
id -> teamId

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +      //display: flex;
)

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/modules/general-info/store/agent-info.js
> +  AGENT_TEAM: (state, getters) => state.agent.team,
А хіба AGENT_TEAM лежить не там же де і AGENT_ID?

2024-04-26 13:56 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +    <ul v-if="isLoaded">
Тут не вистачає перевірки довжини flowsList)
Бо так даммі буде відображатись коли isLoaded false)

2024-04-26 19:45 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +    <ul v-if="isLoaded">
А там ізЛоадед відбувається вже ось за умови:
if (items.length) {
    flowsList.value = items;
    isLoaded.value = true;
  }

2024-04-29 22:38 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +const isLoaded = ref(false);
мені здалось, що ні...

2024-04-29 22:38 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +const flowsList = ref([]);
не працює, так))

2024-04-30 11:32 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/__tests__/flows-tab.spec.js
> +    expect(list.length).toBe(2);
2 -> flowData.length

2024-04-30 11:33 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/__tests__/flows-tab.spec.js
> +    expect(dummy.exists()).toBe(true);
Виходить і flowsData є, і даммі - хіба ні?

2024-04-30 11:34 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +        <div class="flow-item__wrapper">
Назва класів не согласована з назвою компонента(

2024-04-30 11:35 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +const flowsList = ref([]);
Точно, сорян(

2024-04-30 11:37 UTC, Lera24 commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +if (teamId.value) loadFlowsList(teamId.value);
а може у onMounted додати?

2024-05-01 08:48 UTC, Lera24 approved these changes

2024-05-01 11:19 UTC, dlohvinov requested changes

2024-05-01 11:19 UTC, dlohvinov commented on src/app/locale/en/en.js
> +      title: 'Flow schema | Flow schemas',
назва сутності має бути у лібі, може би її використати тут?

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/components/the-agent-info-section.vue
> +      isCallCenter: 'IS_CALL_CENTER_LICENSE',
невірно
напишу далі

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/api/flows.js
може би назвати це файл якось типу TeamTrigger (і відповідно контент змінити теж)
тому що тут він називається флов, і ти очікуєш, що це буде флов
а це не флов -- тут немає апішок флова: гет, сет, апдейт, ітд

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/__tests__/flows-tab.spec.js
> +  it('hide dummy', async () => {
даммі хайдиться коли є якісь дані
в самому тексті немає ніяких згадок про те що дані сетаються

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/__tests__/flows-tab.spec.js
> +  it('renders flows list', async () => {
сюди теж пасувало би покласти додавання даних, щоб було зрозуміло звідки беруться 2 штуки ітема

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/__tests__/flows-tab.spec.js
> +      },
а це точно треба?

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flow-button.vue
> +    await FlowsAPI.run(props.id);
не дуже подобається ідея передавати сюди у компонент просто ід, і слати тільки ід параметром у флов апі
тому що якщо раптом щось ще доведеться докинувати туди -- будуть проблеми
я би передавав повний обʼєкт флова пропсом, і на апі так само

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flow-button.vue
> +  <section class="flow-button">
а чому це секція? 
не розумію, для чого тут цей враппер взагалі

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +        <div class="flows-tab-item__wrapper">
а для чого цей дів?

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +        <wt-divider/>
мені виглядає нелогічним що дівайдер є частиною елемента списку, а не елементом, окремим від елементів списку

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +const isLoaded = ref(false);
я би пропонував додати, бо як це: лоадінг є, а лоадера нема?))

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +const isLoaded = ref(false);
і прошу назвати як і всюди: `isLoading`

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +      }
а чому тут ця умова?

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +      }
якщо список пустий, то лоадінг не закінчився?)

2024-05-01 11:19 UTC, dlohvinov commented on src/ui/modules/userinfo/userinfo.js
> +  IS_CALL_CENTER_LICENSE: (state, getters) => state.license.find((item) => item.prod === 'CALL_CENTER'),
може буть, але тоді не вистачає проміжного кроку
чому компонент лізе в якийсь геттер лєвий "чи є колл центр ліцензія"?
мені здається, пасувало би в сторі фловів написати геттер типу show flows, який би залежав вже від цього геттеру ліцензії

тому що ми хотіли би компоненти звільнити від логічного навантаження зайвого, перенісши його на стор

2024-05-01 14:44 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +        <wt-divider/>
слушно

2024-05-01 14:47 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +        <div class="flows-tab-item__wrapper">
він був для того, щоб гарно розмістити елементи, враховуючи наявність <wt-divider/>
але я переробила) отже, прибрала цей врапєр
дякую за зауваження

2024-05-01 21:11 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +      }
Я поставила його там, бо це якраз лоадед (завантажено), а не лоадінг.
Використала по аналогії з дженерал-інфо-табою, здалось досить зручним.
Тобто мається на увазі, що значення ізЛоадед змінюється на тру, якщо дату завантажено.
Якщо не завантажено - з'являється даммі

2024-05-02 12:49 UTC, liza-pohranichna commented on src/ui/modules/userinfo/userinfo.js
> +  IS_CALL_CENTER_LICENSE: (state, getters) => state.license.find((item) => item.prod === 'CALL_CENTER'),
Дякую за пояснення! Переробила
дійсно, так значно обережніше і гарніше)

2024-05-02 14:27 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/flows/api/flows.js
вирішили залишити, як є

2024-05-02 14:37 UTC, dlohvinov requested changes

2024-05-02 14:37 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +      border-bottom: 1px solid var(--divider-border-color);
краще би використати наш дівайдер, щоб потім не бігати шукати чому колір змінився, а десь не змінився)
пустити циклом враппер, у якому буде лі + дівайдер

2024-05-02 14:37 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/store/flows.js
> +  IS_CALL_CENTER_LICENSE: (state, getters, rootState) => rootState.ui.userinfo.license.find((item) => item.prod === 'CALL_CENTER'),
це має бути в юзерінфо)

2024-05-02 14:37 UTC, dlohvinov commented on src/ui/modules/info-section/modules/flows/store/flows.js
> +  ALLOW_FLOWS: (state, getters, rootState, rootGetters) => (
а ось це добре)

2024-05-02 18:06 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/flows/components/flows-tab.vue
> +        class="flows-tab-item-wrapper"
думаю, ось тут назва класів може бути основним спірним моментом)

2024-05-03 07:48 UTC, dlohvinov commented on src/ui/modules/info-section/components/the-agent-info-section.vue
> +        text: this.$t(`WebitelApplications.${WebitelApplications.ADMIN}.sections.${AdminSections.FLOW}`),
я тільки зараз помітив, це не та локаль :(

2024-05-03 07:48 UTC, dlohvinov commented on src/ui/modules/info-section/components/the-agent-info-section.vue
> +        text: this.$t(`WebitelApplications.${WebitelApplications.ADMIN}.sections.${AdminSections.FLOW}`),
https://github.com/webitel/webitel-ui-sdk/blob/master/src/locale/en/en.js#L142 -- ось тут мала би ще лежати назва флова

2024-05-03 08:25 UTC, liza-pohranichna commented on src/ui/modules/info-section/components/the-agent-info-section.vue
> +        text: this.$tc('objects.flow.name', 2),
змінила

2024-05-03 08:28 UTC, merged