Feature/hotkeys
webitel/cc-workspaces pull request #394
Opened 2024-05-08 16:35 UTC by RomanZaritskyi

2024-05-09 08:48 UTC, Lera24 commented on src/app/the-app.vue
> +import { mapActions } from 'vuex/dist/vuex.cjs.js';
а нащо це?)

2024-05-09 08:48 UTC, Lera24 commented on src/ui/modules/queue-section/components/the-agent-queue-section.vue
> +    const subscribers = [
Мені просить у окремий метод)

2024-05-09 08:48 UTC, Lera24 commented on src/ui/modules/queue-section/components/the-agent-queue-section.vue
> +      id="some-id"
а це навіщо?)

2024-05-09 08:48 UTC, Lera24 commented on src/ui/modules/work-section/modules/call/components/call-footer.vue
> +    const subscribers = [
Винеси будь ласочка окремо усюди)

2024-05-09 08:48 UTC, Lera24 commented on src/ui/modules/queue-section/modules/call-queue/components/active-queue/active-queue-container.vue
> +      combinations: (state) => state.hotkeys,
а це десь викликається?

2024-05-09 08:48 UTC, Lera24 commented on src/ui/modules/queue-section/modules/call-queue/components/the-agent-call-queue.vue
> +onUnmounted(() => {
hoks life cycle йдуть в кінці компонента, перевір усюди)

2024-05-09 08:48 UTC, Lera24 commented on src/ui/modules/work-section/modules/chat/components/chat-footer/chat-footer.vue
>    destroyed() {
А це не одне і те саме з unmounted?)

2024-05-09 08:48 UTC, Lera24 commented on src/ui/modules/work-section/modules/job/components/job-footer/job-footer.vue
> +  <button type="button" @click="() => console.log(unsubscribers)">Test</button>
Мабуть тестував)

2024-05-09 09:29 UTC, RomanZaritskyi commented on src/app/the-app.vue
> +import { mapActions } from 'vuex/dist/vuex.cjs.js';
Все вірно))
не треба

2024-05-09 09:31 UTC, RomanZaritskyi commented on src/ui/modules/queue-section/components/the-agent-queue-section.vue
> +      id="some-id"
Не треба)
я вже й не пам'ятаю шо я хотів з цим зробити

2024-05-09 11:47 UTC, RomanZaritskyi commented on src/ui/modules/queue-section/modules/call-queue/components/active-queue/active-queue-container.vue
> +      combinations: (state) => state.hotkeys,
Ноуп

2024-05-09 13:08 UTC, RomanZaritskyi commented on src/ui/modules/work-section/modules/chat/components/chat-footer/chat-footer.vue
>    destroyed() {
Вичитав, що destroyed вже не використовують.
Взагальному то получається що видаляти лісенер треба на beforeUnmount, так як unmount це SSR хук.

2024-05-09 15:02 UTC, dlohvinov requested changes
гарна, чиста робота!
фікси -- мінорні)

2024-05-09 15:02 UTC, dlohvinov commented on src/ui/modules/work-section/modules/job/components/job-footer/job-footer.vue
> +  <button type="button" @click="() => console.log(unsubscribers)">Test</button>
я би теж просив це забрати))

2024-05-09 15:02 UTC, dlohvinov commented on src/ui/modules/queue-section/components/the-agent-queue-section.vue
> +    unsubscribers: [],
я би пропонував конкретизувати назву, що воно саме до хоткеїв
наприклад `hotkeyUnsubscribers`, `unsubHotkeyListeners`, шось таке

2024-05-09 17:28 UTC, RomanZaritskyi commented on src/ui/hotkeys/HotkeysActiom.enum.js
> +  SELECT: 'SELECT',
Насправді в рамках цієї задачі я їх не використовую, тому поки приберу.

2024-05-09 17:37 UTC, RomanZaritskyi commented on src/ui/hotkeys/useHotkeys.js
> +  else if (event.altKey && event.code === 'KeyH') {
Я хотів щоб використувувся один модифікатор для всіх команд. Мені здалось це зручним.
На контрол багато нативного всього навішано.
На шифт я побоявся бо наприклад в чатах, треба відписувати, якісь літери будуть великими, тобто будуть використовуватись комбінації з шифтом. Хоча може спробувати вішати лісенер не на ```window``` а на елемент компонента... хм.
На ``` alt ``` майже нічого не навішано окрім відкриття налаштувань ```alt+e```. Тому вирішив використати саме ```alt```.

2024-05-09 17:41 UTC, RomanZaritskyi commented on src/ui/modules/queue-section/components/the-agent-queue-section.vue
> +    unsubscribers: [],
Пропозицію підтримую, ``` hotkeyUnsubscribers``` якщо не проти.

2024-05-10 05:54 UTC, dlohvinov approved these changes

2024-05-10 05:54 UTC, merged