Refactor/chat module [WTEL-5593, WTEL-5431, WTEL-5555]
webitel/cc-workspaces pull request #560
Opened 2024-12-24 22:37 UTC by liza-pohranichna

2024-12-26 08:47 UTC, stanislav-kozak requested changes

2024-12-26 08:47 UTC, stanislav-kozak commented on src/features/modules/chat/store/chat-media.js
> +  INITIALIZE_CHAT_PLAYERS: (context, { player, chat = context.getters.CHAT_ON_WORKSPACE }) => {
В параметрах я бачу chat який ти сетиш по дефолту із гетера, та я не бачу щоб ти десь далі передавала параметрами цей чат, точно він нам потрібен в параметрах?

2024-12-26 08:47 UTC, stanislav-kozak commented on src/features/modules/chat/store/chat-media.js
> +  CLEAN_CHAT_PLAYERS: (context, { chat = context.getters.CHAT_ON_WORKSPACE } = {}) => {
Так же тут я не бачу щоб ти при використані передавала chat

2024-12-26 08:47 UTC, stanislav-kozak commented on src/features/modules/chat/store/chat-media.js
> +  ATTACH_PLAYER_TO_CHAT: (context, { player, chat = context.getters.CHAT_ON_WORKSPACE }) => {
Те ж саме що і коментар више, я не знайшов де б ти передавала чат в цей екшен

2024-12-26 08:47 UTC, stanislav-kozak commented on src/features/modules/chat/store/chat-media.js
> +      if (chatPlayer !== player) chatPlayer.pause();
Можливо краще використати deepEqual?

2024-12-26 08:47 UTC, stanislav-kozak commented on src/features/modules/chat/store/chat-media.js
> +      if (chatPlayer !== player) chatPlayer.pause();
Або взагалі по ід порівнювати, бо так виходить що ти ссилки порівнюєш

2024-12-26 08:47 UTC, stanislav-kozak commented on src/ui/modules/work-section/modules/chat/chat-header/chat-header.vue
> +        :href="contactLink(chat?.contact?.id)"
Тут можна замінити chat?.contact?.id => chat.contact.id бо в v-if ти вже то перевіряєш

2024-12-26 08:47 UTC, stanislav-kozak commented on src/ui/modules/work-section/modules/chat/chat-messaging/chat-messaging.vue
> +      :contact="chat?.contact"
Також в :contact="chat?.contact" можна без ? передавати параметр

2024-12-26 14:31 UTC, liza-pohranichna commented on src/features/modules/chat/store/chat-media.js
> +  INITIALIZE_CHAT_PLAYERS: (context, { player, chat = context.getters.CHAT_ON_WORKSPACE }) => {
зрозуміла тебе
я пропоную залишити його, як є, для більшої гнучкості. бо, як на мене, скорочення коду в цьому випадку багато вихлопу не дасть, а залишити цю гнучкість - не зайве.
до того ж, тут така штука, що я ці екшени виключно перенесла з одного файлу в інший, впорядкувавши
а писав їх раніше Даня, то я допускаю, шо він передбачав якийсь функціонал цим

2024-12-26 15:17 UTC, stanislav-kozak approved these changes

2024-12-27 12:59 UTC, dlohvinov approved these changes

2025-02-11 14:52 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/chat-header/chat-header.vue
> +    displayName() {
це так і було

2025-02-11 14:52 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/chat-header/chat-header.vue
> +    displayNumber() {
це так і було

2025-02-11 15:19 UTC, Lera24 commented on src/features/modules/chat/store/chat-media.js
> +    chat.players = player ? [player] : [];
Ліза, в мене насправді є питання до цього і методів ті що нижче.
Їм точно місце в сторі? 

Типу екшини мали б викликати мутації, якісь дії робити саме з данними стору.
А так ти прокидуєш чат і його ж і міняєш, але що таке чат саме в рамках стору? 

Мені це виглядає як локальні для компонентів методи. Може їх винести в окремий файл, але ось чи місце їм саме в сторі, не впенвнена

2025-02-11 15:19 UTC, Lera24 commented on src/app/api/agent-workspace/endpoints/communications/CommunicationsAPIRepository.js
>  import { CommunicationTypeServiceApiFactory } from 'webitel-sdk';
а це не ті комунікації що в таймлайнах? 
може б в лібу винести?

2025-02-11 15:19 UTC, Lera24 commented on src/app/api/agent-workspace/endpoints/users/UsersAPIRepository.js
> +const getLookup = (params) => getUsers({
це я так розумію і була апішка, але все одно)
називається файл що це юзери (хоча так розумію не ті наші юзери що в лібі)
всередині фабрика використовується з назвою агенти
+ всередині виклик через інстанс не через фабрику

якось мені виглядає тут би трішки навести порядок)
або поясни як я помиляюсь пліс)

2025-02-11 15:19 UTC, Lera24 commented on src/ui/modules/work-section/modules/chat/chat-header/chat-header.vue
> +        console.log('this.chat.contact:', this.chat.contact);
))

2025-02-11 15:19 UTC, Lera24 commented on src/ui/modules/work-section/modules/chat/scripts/getLinkedContact.js
> +    console.log('SCRIPT getLinkedContact: Can`t get contact by User Id. Error:', error);
може throw error?

2025-02-11 15:19 UTC, Lera24 commented on src/ui/modules/work-section/modules/chat/scripts/getLinkedContact.js
> +  else return await getContactByUserId(task);
мені "трішки ріже око" return await
мені б пасувало await винести в змінну і її повернути, а там вже на твій смак)

2025-02-11 16:01 UTC, liza-pohranichna commented on src/features/modules/chat/store/chat-media.js
> +    chat.players = player ? [player] : [];
Дивись, це не новий функціонал. Величезна частина змін в цьому ПРі це просто перенесення з одного файлику в інший, власне, як і цей файл. Весь цей код переміщений з файлу store/chat, бо він був просто на міль'ярд строк.
Якщо чесно, я не вважаю доцільним зараз переробляти методи ініціалізації та використання плеєра, адже ці методи перевикористовуються в компонентах. І в тих компонентах, де вони є, наразі вже також багато логіки. 
+ це досить старий код, який, як я бачу, справно працює. Тому я не готова наразі це рухати

2025-02-12 19:05 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/scripts/getLinkedContact.js
> +    console.log('SCRIPT getLinkedContact: Can`t get contact by User Id. Error:', error);
спершу теж так подумала, але потім зрозуміла, що оцей конкретний скріпт буде спрацьовувати в дуже специфічних кейсах. І звичні помилку можуть тіки плутати. А так типу в консоль заходиш - і все написано

2025-02-12 19:06 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/scripts/getLinkedContact.js
> +  else return await getContactByUserId(task);
згодна тут, переробила

2025-02-13 11:36 UTC, liza-pohranichna commented on src/app/api/agent-workspace/endpoints/users/UsersAPIRepository.js
> +const getLookup = (params) => getUsers({
домовились! відкрию

2025-02-13 11:36 UTC, Lera24 approved these changes

2025-02-13 16:23 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/chat-header/chat-header.vue
>      },
@dlohvinov цікавить найбільше твоя думка щодо цього

2025-02-13 16:24 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/scripts/getLinkedContact.js
> +
@dlohvinov звісно, цього)

2025-02-13 17:35 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/chat-messaging/chat-messaging.vue
> +    },
@dlohvinov і оцього

2025-02-13 17:35 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/scripts/getLinkedContact.js
> +  };
@dlohvinov звісно, всього цього файлу)

2025-02-13 19:56 UTC, dlohvinov commented on src/ui/modules/info-section/modules/client-info/components/client-info-tab.vue
> +      isChatClosed: 'IS_CHAT_ON_WORKSPACE_WAS_CLOSED',
хєхнув з IS_...._WAS :):)

2025-02-13 19:56 UTC, dlohvinov commented on src/ui/modules/work-section/modules/chat/chat-header/chat-header.vue
> +    },
без питань, гарно)
єдине шо, це можна було би розмутити через комп'ютед:
так само сетати в локальну змінну контакт, завантажений з беку
але на юі кидати комп'ютед з `this.chat.contact || this.localContact`, чи щось подібне

мені цей спросіб виглядає трішки кращим, тому що він напряму юзає зіс.чат.контакт, а не сетає його в нову змінну

але це просто як трішки інший спосіб це зробити, і, взагалі не принциповов)

2025-02-13 19:56 UTC, dlohvinov commented on src/ui/modules/work-section/modules/chat/chat-messaging/chat-messaging.vue
> +    },
а от тут вже трохи стрьомна тєма, що той самий код -- копіпаста. хотілося б його мати в одному, умовно, файлику, і реюзнути той файлик

але, не критично, насправді

2025-02-13 19:56 UTC, dlohvinov commented on src/ui/modules/work-section/modules/chat/scripts/getLinkedContact.js
> +  }
без throw помилка не полетить далі, і, загубиться

2025-02-13 21:54 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/scripts/getLinkedContact.js
> +  }
Поексперементувала, спробувала і з throw, і з console.error, і все разом) якщо залишити лише з console.error, то викидує помилку, як і зазвичай. Показує по 2 сповіщення (в консолі) на кожен кейс + вспливаючу нотіфікашку теж.

2025-02-13 21:55 UTC, liza-pohranichna commented on src/ui/modules/work-section/modules/chat/chat-header/chat-header.vue
> +    },
Насправді, початково пробувала якраз через композібл, але шось у мене на тому етапі з ним не склалось, вже не пам'ятаю чому саме...Тому згодна з тобою

2025-02-14 11:57 UTC, liza-pohranichna commented on src/ui/modules/info-section/modules/client-info/components/client-info-tab.vue
> +      isChatClosed: 'IS_CHAT_ON_WORKSPACE_WAS_CLOSED',
шото я рілі перемудрила

2025-02-17 10:15 UTC, dlohvinov approved these changes

2025-02-17 11:51 UTC, merged